Pytorch Fundamentals

In [1]:
print("I am excited to learn pytorch")

I am excited to learn pytorch


In [2]:
!nvidia-smi

Wed Oct 18 17:46:32 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.0.1+cu118


#introduction to tensors
#Creating tensors

In [4]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])

In [10]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])

In [14]:
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [15]:
TENSOR.ndim

3

#random tensors

In [16]:
random_tensor = torch.rand(1000,100)

In [17]:
random_tensor

tensor([[0.6649, 0.7459, 0.9322,  ..., 0.8324, 0.1975, 0.7547],
        [0.5481, 0.3495, 0.4232,  ..., 0.4436, 0.3195, 0.7089],
        [0.9399, 0.7508, 0.8662,  ..., 0.1770, 0.2433, 0.3570],
        ...,
        [0.2744, 0.0375, 0.7329,  ..., 0.6339, 0.1320, 0.8147],
        [0.7923, 0.0570, 0.0577,  ..., 0.0532, 0.1241, 0.9391],
        [0.0305, 0.8221, 0.0674,  ..., 0.8913, 0.8547, 0.8565]])

 #creatingf random tensor with dimension of a image

In [18]:
random_image_size_tensor = torch.rand(size = (224,224,3))

In [19]:
random_image_size_tensor

tensor([[[0.9032, 0.0316, 0.7008],
         [0.6766, 0.6196, 0.7259],
         [0.4619, 0.7212, 0.0632],
         ...,
         [0.5390, 0.4456, 0.9993],
         [0.2702, 0.1068, 0.4932],
         [0.2689, 0.6942, 0.8170]],

        [[0.5250, 0.1530, 0.0088],
         [0.0275, 0.5148, 0.5717],
         [0.0881, 0.8978, 0.6999],
         ...,
         [0.1699, 0.5690, 0.8460],
         [0.2706, 0.1723, 0.9385],
         [0.2505, 0.5304, 0.7765]],

        [[0.3730, 0.1593, 0.8091],
         [0.3421, 0.5068, 0.4812],
         [0.0018, 0.5772, 0.8935],
         ...,
         [0.1305, 0.2262, 0.5602],
         [0.3762, 0.5599, 0.5320],
         [0.8787, 0.9479, 0.1458]],

        ...,

        [[0.2487, 0.5214, 0.8797],
         [0.3682, 0.3397, 0.0201],
         [0.9996, 0.9913, 0.6699],
         ...,
         [0.7943, 0.4099, 0.6260],
         [0.4173, 0.5090, 0.5353],
         [0.9211, 0.0141, 0.0231]],

        [[0.1677, 0.2550, 0.2176],
         [0.2521, 0.4592, 0.5338],
         [0.

In [20]:
random_image_size_tensor.ndim

3

In [21]:
random_image_size_tensor.size

<function Tensor.size>

In [22]:
TENSOR.dtype

torch.int64

## reshaping stacking squeezing and unsquezzing

#reshape - reshape tensor to a defined shape
#view- return a view of an input tensor of certain

In [23]:
import torch
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [24]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [25]:
x_stacked = torch.stack([x,x,x,x],dim = -1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [26]:
x_reshaped.shape

torch.Size([3, 3])

In [27]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [28]:
x_reshaped.squeeze()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [29]:
x_reshaped=x_reshaped.reshape([1,9])

In [30]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
x_orignal = torch.rand(size=(224,224,3))

In [32]:
x_permuted = x_orignal.permute(2,0,1)

In [33]:
x_permuted

tensor([[[0.3392, 0.4262, 0.1968,  ..., 0.0744, 0.7941, 0.2450],
         [0.0302, 0.1584, 0.4003,  ..., 0.1211, 0.1408, 0.8249],
         [0.7869, 0.5595, 0.6311,  ..., 0.3091, 0.1317, 0.8475],
         ...,
         [0.1149, 0.5230, 0.8867,  ..., 0.6836, 0.0168, 0.9309],
         [0.2232, 0.1432, 0.1761,  ..., 0.3700, 0.6794, 0.1029],
         [0.8959, 0.0360, 0.7144,  ..., 0.4624, 0.3442, 0.3368]],

        [[0.9844, 0.4644, 0.6901,  ..., 0.3853, 0.5270, 0.4402],
         [0.9163, 0.5050, 0.9394,  ..., 0.1135, 0.3827, 0.2423],
         [0.7770, 0.8532, 0.2768,  ..., 0.2727, 0.0491, 0.4225],
         ...,
         [0.0626, 0.5724, 0.9486,  ..., 0.3787, 0.5329, 0.3546],
         [0.6624, 0.5890, 0.1190,  ..., 0.7703, 0.0408, 0.3366],
         [0.9083, 0.4928, 0.0900,  ..., 0.7664, 0.4700, 0.3777]],

        [[0.1713, 0.3751, 0.0886,  ..., 0.2205, 0.3731, 0.5833],
         [0.3062, 0.4385, 0.6286,  ..., 0.9979, 0.0640, 0.0238],
         [0.0435, 0.7849, 0.4533,  ..., 0.4955, 0.1692, 0.

##INDEXING

In [34]:
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [35]:
x[0,1]

tensor([4, 5, 6])

#lets index on the most inner bracket

In [36]:
x[:,-1]

tensor([[7, 8, 9]])

In [37]:
torch.rand(3,3)

tensor([[0.7584, 0.2229, 0.4029],
        [0.2602, 0.7741, 0.1318],
        [0.4463, 0.3269, 0.2688]])

In [38]:
random_tensor_A = torch.rand(3,3)
random_tensor_B = torch.rand(3,3)

In [39]:
random_tensor_A == random_tensor_B

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [40]:
random_seed = 0
torch.manual_seed(random_seed)


In [41]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [42]:
device

'cuda'

In [43]:
akshit = torch.rand(7,7)
akshit

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [44]:
goyal = torch.rand(1,7)

In [45]:
akshit_goyal = torch.mm(akshit,torch.transpose(goyal, 0, 1))

In [46]:
print(akshit_goyal)
akshit_goyal.shape

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


torch.Size([7, 1])

In [47]:
 torch.cuda.manual_seed(1234)

In [48]:
akshit = torch.rand(2, 3)
goyal = torch.rand(2, 3)

In [50]:
akshit.to("cuda:0")
goyal.to("cuda:0")

tensor([[0.2038, 0.6511, 0.7745],
        [0.4369, 0.5191, 0.6159]], device='cuda:0')

In [51]:
akshit_goyal = torch.mm(akshit,torch.transpose(goyal, 0, 1))

In [52]:
akshit_goyal

tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]])